### ISSUE TITLE
clone template X times

### ISSUE THREAD

**Issue by jctanner** [imsweb/ezmomi#10]
If my PR to #3 is accepted, I'd like to further extend the clone subcommand to include a --count parameter. The purpose would be to allow the end user to clone a template multiple times in the same command. 

Example:
```
emomzi clone --template=foo --hostname=bar-%d --count=4
Cloning foo to new host bar-0
Cloning foo to new host bar-1
Cloning foo to new host bar-2
Cloning foo to new host bar-3
Waiting for bar-0 to obtain an IP address
Waiting for bar-1 to obtain an IP address
Waiting for bar-2 to obtain an IP address
Waiting for bar-4 to obtain an IP address
bar-0 10.0.0.100
bar-1 10.0.0.101
bar-2 10.0.0.102
bar-3 10.0.0.103
```

**Comment by snobear** [comment]
Thanks for the suggestions @jctanner , but I'm going to close this for now. I like the idea but it adds complexity to this tool, e.g. static IP assignment, that could easily be achieved with a wrapper script.
