### ISSUE TITLE
Not really an issue: Request

### ISSUE THREAD

**Issue by v1gnesh** [imsweb/ezmomi#40]
Hi,

Any slightest chance that this will be updated to work with RHN Satellite API for doing Linux builds.
For estates that manage Windows and Linux's differently...

**Comment by snobear** [comment]
Hi @v1gnesh, I don't know much about RHN Satellite. Does it use vSphere for managing VMs?  If so, could you change the server/port settings to point to it in the RHN cloud? Or does it have a separate interface and API in front of vSphere?  Or not vSphere at all?

**Comment by v1gnesh** [comment]
Hola,

It does, in my shop at least. VM "containers" are created with NIC's and that's then used by the *nix teams to kickstart their RHEL from Satellite.
It has a separate interface and API in general, not specifically for vSphere.

That said, Satellite 6 brought in the ability to provision on ESXi's. So I suppose *nix's can stay separate from any vSphere automation.

Also, this may already be in the code; just a quick Q: Does ezmomi allow sysprep for Windows VM builds?

**Comment by snobear** [comment]
No plans to implement this.
