### ISSUE TITLE
Can I get a dump of a guest properties?

### ISSUE THREAD

**Issue by aseques** [imsweb/ezmomi#63]
I would like to get an overview of the guest properties before doing a clone, I've had a look at eh source but couldn't find it.
Is it possible with the current version?

**Comment by snobear** [comment]
Hi @aseques - hmm you could try adding `--debug`, but that would still go through with the clone, and I'm not 100% sure we have debug output for the guest itself.

If not, a PR would be welcome. Not sure if it would fit in any of the existing subcommand sections, so would probably be best under say, `ezmomi inspect --template centos7`.

**Comment by aseques** [comment]
Thanks for your reply, unfortunately at this point I can't work on this, I'll resort to getting the information manually meanwhile
