### ISSUE TITLE
"Install via github" instructions --> Error: "fatal: Could not read from remote repository."

### ISSUE THREAD

**Issue by github-12341234** [imsweb/ezmomi#74]
$ git clone git@github.com:imsweb/ezmomi.git
Cloning into 'ezmomi'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by snobear** [comment]
Try the https endpoint instead:

```
git clone https://github.com/imsweb/ezmomi.git
```

I'll actually change the README to this since its preferred.  

You'll need an ssh public key added to your github profile in order to use the ssh endpoint per https://help.github.com/articles/which-remote-url-should-i-use/,

**Comment by github-12341234** [comment]
Works for me!  Thanks!

**Comment by github-12341234** [comment]
You may also want to change the README to include this: 
virtualenv --no-site-packages -p python2.7 ezmomi

Without '-p python2.7' the virtualenv command fails on my Mac running OS X 10.11.6

**Comment by snobear** [comment]
Good info, thanks,  I'll see if `-p python2.7` works on Linux and add that flag in, otherwise I'll just make a side note in the README about it.

**Comment by snobear** [comment]
Works on Linux as well. :+1:  Added to the README install notes.
